# Generated by Django 3.2.5 on 2021-08-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='photo_auther',
            new_name='photo_author',
        ),
    ]
